dist: trusty
sudo: required
language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1
  - nightly
notifications:
  email: false
install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"
#  - "export DISPLAY=:99.0"
  - sudo apt-add-repository -y ppa:keithw/glfw3
  - sudo apt-get update
  - sudo apt-get install libfreeimage-dev libatlas3gf-base libfftw3-dev cmake libglfw3-dev mesa-utils
  - wget -q http://arrayfire.s3.amazonaws.com/3.5.1/ArrayFire-v3.5.1_Linux_x86_64.sh
  - ls -l
  - sudo chmod +x ArrayFire-v3.5.1_Linux_x86_64.sh
  - sudo ./ArrayFire-v3.5.1_Linux_x86_64.sh --exclude-subdir --prefix=/usr/local
before_script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/
  # - julia -e 'using Pkg; Pkg.add("AutoDiffSource");'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("ArrayFire")); using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("ArrayFire")); using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
